<?php
/**
 * AgreementWorkTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Finance
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Finance API
 *
 * ConnectWise Finance API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\Finance;

/**
 * AgreementWorkTypeTest Class Doc Comment
 *
 * @category    Class */
// * @description AgreementWorkType
/**
 * @package     Spinen\ConnectWise\Clients\Finance
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AgreementWorkTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "AgreementWorkType"
     */
    public function testAgreementWorkType()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "work_type"
     */
    public function testPropertyWorkType()
    {

    }

    /**
     * Test attribute "location_id"
     */
    public function testPropertyLocationId()
    {

    }

    /**
     * Test attribute "rate_type"
     */
    public function testPropertyRateType()
    {

    }

    /**
     * Test attribute "bill_time"
     */
    public function testPropertyBillTime()
    {

    }

    /**
     * Test attribute "rate"
     */
    public function testPropertyRate()
    {

    }

    /**
     * Test attribute "hours_max"
     */
    public function testPropertyHoursMax()
    {

    }

    /**
     * Test attribute "hours_min"
     */
    public function testPropertyHoursMin()
    {

    }

    /**
     * Test attribute "round_bill_hours"
     */
    public function testPropertyRoundBillHours()
    {

    }

    /**
     * Test attribute "overage_rate"
     */
    public function testPropertyOverageRate()
    {

    }

    /**
     * Test attribute "overage_rate_type"
     */
    public function testPropertyOverageRateType()
    {

    }

    /**
     * Test attribute "agreement_limit"
     */
    public function testPropertyAgreementLimit()
    {

    }

    /**
     * Test attribute "site"
     */
    public function testPropertySite()
    {

    }

    /**
     * Test attribute "effective_date"
     */
    public function testPropertyEffectiveDate()
    {

    }

    /**
     * Test attribute "ending_date"
     */
    public function testPropertyEndingDate()
    {

    }

    /**
     * Test attribute "agreement_id"
     */
    public function testPropertyAgreementId()
    {

    }

    /**
     * Test attribute "company"
     */
    public function testPropertyCompany()
    {

    }

    /**
     * Test attribute "_info"
     */
    public function testPropertyInfo()
    {

    }

}
