<?php
/**
 * AgreementTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Finance
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Finance API
 *
 * ConnectWise Finance API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\Finance;

/**
 * AgreementTypeTest Class Doc Comment
 *
 * @category    Class */
// * @description AgreementType
/**
 * @package     Spinen\ConnectWise\Clients\Finance
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AgreementTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "AgreementType"
     */
    public function testAgreementType()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "prefix_suffix_option"
     */
    public function testPropertyPrefixSuffixOption()
    {

    }

    /**
     * Test attribute "default_flag"
     */
    public function testPropertyDefaultFlag()
    {

    }

    /**
     * Test attribute "inactive_flag"
     */
    public function testPropertyInactiveFlag()
    {

    }

    /**
     * Test attribute "pre_payment_flag"
     */
    public function testPropertyPrePaymentFlag()
    {

    }

    /**
     * Test attribute "invoice_pre_suffix"
     */
    public function testPropertyInvoicePreSuffix()
    {

    }

    /**
     * Test attribute "location_id"
     */
    public function testPropertyLocationId()
    {

    }

    /**
     * Test attribute "business_unit_id"
     */
    public function testPropertyBusinessUnitId()
    {

    }

    /**
     * Test attribute "restrict_location_flag"
     */
    public function testPropertyRestrictLocationFlag()
    {

    }

    /**
     * Test attribute "restrict_department_flag"
     */
    public function testPropertyRestrictDepartmentFlag()
    {

    }

    /**
     * Test attribute "sla_id"
     */
    public function testPropertySlaId()
    {

    }

    /**
     * Test attribute "application_units"
     */
    public function testPropertyApplicationUnits()
    {

    }

    /**
     * Test attribute "application_limit"
     */
    public function testPropertyApplicationLimit()
    {

    }

    /**
     * Test attribute "application_cycle"
     */
    public function testPropertyApplicationCycle()
    {

    }

    /**
     * Test attribute "application_unlimited_flag"
     */
    public function testPropertyApplicationUnlimitedFlag()
    {

    }

    /**
     * Test attribute "one_time_flag"
     */
    public function testPropertyOneTimeFlag()
    {

    }

    /**
     * Test attribute "cover_agreement_time_flag"
     */
    public function testPropertyCoverAgreementTimeFlag()
    {

    }

    /**
     * Test attribute "cover_agreement_product_flag"
     */
    public function testPropertyCoverAgreementProductFlag()
    {

    }

    /**
     * Test attribute "cover_agreement_expense_flag"
     */
    public function testPropertyCoverAgreementExpenseFlag()
    {

    }

    /**
     * Test attribute "cover_sales_tax_flag"
     */
    public function testPropertyCoverSalesTaxFlag()
    {

    }

    /**
     * Test attribute "carry_over_unused_flag"
     */
    public function testPropertyCarryOverUnusedFlag()
    {

    }

    /**
     * Test attribute "allow_overruns_flag"
     */
    public function testPropertyAllowOverrunsFlag()
    {

    }

    /**
     * Test attribute "expired_days"
     */
    public function testPropertyExpiredDays()
    {

    }

    /**
     * Test attribute "limit"
     */
    public function testPropertyLimit()
    {

    }

    /**
     * Test attribute "expire_when_zero"
     */
    public function testPropertyExpireWhenZero()
    {

    }

    /**
     * Test attribute "charge_to_firm_flag"
     */
    public function testPropertyChargeToFirmFlag()
    {

    }

    /**
     * Test attribute "employee_comp_rate"
     */
    public function testPropertyEmployeeCompRate()
    {

    }

    /**
     * Test attribute "employee_comp_not_exceed"
     */
    public function testPropertyEmployeeCompNotExceed()
    {

    }

    /**
     * Test attribute "comp_hourly_rate"
     */
    public function testPropertyCompHourlyRate()
    {

    }

    /**
     * Test attribute "comp_limit_amount"
     */
    public function testPropertyCompLimitAmount()
    {

    }

    /**
     * Test attribute "bill_cycle_id"
     */
    public function testPropertyBillCycleId()
    {

    }

    /**
     * Test attribute "bill_one_time_flag"
     */
    public function testPropertyBillOneTimeFlag()
    {

    }

    /**
     * Test attribute "bill_terms_id"
     */
    public function testPropertyBillTermsId()
    {

    }

    /**
     * Test attribute "invoicing_cycle"
     */
    public function testPropertyInvoicingCycle()
    {

    }

    /**
     * Test attribute "bill_amount"
     */
    public function testPropertyBillAmount()
    {

    }

    /**
     * Test attribute "taxable_flag"
     */
    public function testPropertyTaxableFlag()
    {

    }

    /**
     * Test attribute "restrict_down_payment_flag"
     */
    public function testPropertyRestrictDownPaymentFlag()
    {

    }

    /**
     * Test attribute "invoice_description"
     */
    public function testPropertyInvoiceDescription()
    {

    }

    /**
     * Test attribute "top_comment_flag"
     */
    public function testPropertyTopCommentFlag()
    {

    }

    /**
     * Test attribute "bottom_comment_flag"
     */
    public function testPropertyBottomCommentFlag()
    {

    }

    /**
     * Test attribute "work_role"
     */
    public function testPropertyWorkRole()
    {

    }

    /**
     * Test attribute "work_type"
     */
    public function testPropertyWorkType()
    {

    }

    /**
     * Test attribute "project_type_id"
     */
    public function testPropertyProjectTypeId()
    {

    }

    /**
     * Test attribute "invoice_template_setup_id"
     */
    public function testPropertyInvoiceTemplateSetupId()
    {

    }

    /**
     * Test attribute "bill_time"
     */
    public function testPropertyBillTime()
    {

    }

    /**
     * Test attribute "bill_expenses"
     */
    public function testPropertyBillExpenses()
    {

    }

    /**
     * Test attribute "bill_products"
     */
    public function testPropertyBillProducts()
    {

    }

    /**
     * Test attribute "billable_time_invoice_flag"
     */
    public function testPropertyBillableTimeInvoiceFlag()
    {

    }

    /**
     * Test attribute "billable_expense_invoice_flag"
     */
    public function testPropertyBillableExpenseInvoiceFlag()
    {

    }

    /**
     * Test attribute "billable_product_invoice_flag"
     */
    public function testPropertyBillableProductInvoiceFlag()
    {

    }

    /**
     * Test attribute "copy_work_roles_flag"
     */
    public function testPropertyCopyWorkRolesFlag()
    {

    }

    /**
     * Test attribute "copy_work_types_flag"
     */
    public function testPropertyCopyWorkTypesFlag()
    {

    }

    /**
     * Test attribute "_info"
     */
    public function testPropertyInfo()
    {

    }

}
