<?php
/**
 * BatchTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Finance
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Finance API
 *
 * ConnectWise Finance API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\Finance;

/**
 * BatchTest Class Doc Comment
 *
 * @category    Class */
// * @description Batch
/**
 * @package     Spinen\ConnectWise\Clients\Finance
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BatchTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Batch"
     */
    public function testBatch()
    {

    }

    /**
     * Test attribute "thru_date"
     */
    public function testPropertyThruDate()
    {

    }

    /**
     * Test attribute "transactions_closed_date"
     */
    public function testPropertyTransactionsClosedDate()
    {

    }

    /**
     * Test attribute "location_id"
     */
    public function testPropertyLocationId()
    {

    }

    /**
     * Test attribute "summarize_invoices"
     */
    public function testPropertySummarizeInvoices()
    {

    }

    /**
     * Test attribute "included_invoice_ids"
     */
    public function testPropertyIncludedInvoiceIds()
    {

    }

    /**
     * Test attribute "included_expense_ids"
     */
    public function testPropertyIncludedExpenseIds()
    {

    }

    /**
     * Test attribute "included_product_ids"
     */
    public function testPropertyIncludedProductIds()
    {

    }

    /**
     * Test attribute "excluded_invoice_ids"
     */
    public function testPropertyExcludedInvoiceIds()
    {

    }

    /**
     * Test attribute "excluded_expense_ids"
     */
    public function testPropertyExcludedExpenseIds()
    {

    }

    /**
     * Test attribute "excluded_product_ids"
     */
    public function testPropertyExcludedProductIds()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "batch_identifier"
     */
    public function testPropertyBatchIdentifier()
    {

    }

    /**
     * Test attribute "export_invoices_flag"
     */
    public function testPropertyExportInvoicesFlag()
    {

    }

    /**
     * Test attribute "export_expenses_flag"
     */
    public function testPropertyExportExpensesFlag()
    {

    }

    /**
     * Test attribute "export_products_flag"
     */
    public function testPropertyExportProductsFlag()
    {

    }

    /**
     * Test attribute "closed_flag"
     */
    public function testPropertyClosedFlag()
    {

    }

    /**
     * Test attribute "_info"
     */
    public function testPropertyInfo()
    {

    }

}
