<?php
/**
 * GLExportTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Finance
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Finance API
 *
 * ConnectWise Finance API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\Finance;

/**
 * GLExportTest Class Doc Comment
 *
 * @category    Class */
// * @description GLExport
/**
 * @package     Spinen\ConnectWise\Clients\Finance
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GLExportTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "GLExport"
     */
    public function testGLExport()
    {

    }

    /**
     * Test attribute "export_settings"
     */
    public function testPropertyExportSettings()
    {

    }

    /**
     * Test attribute "vendors"
     */
    public function testPropertyVendors()
    {

    }

    /**
     * Test attribute "customers"
     */
    public function testPropertyCustomers()
    {

    }

    /**
     * Test attribute "transactions"
     */
    public function testPropertyTransactions()
    {

    }

    /**
     * Test attribute "expenses"
     */
    public function testPropertyExpenses()
    {

    }

    /**
     * Test attribute "expense_bills"
     */
    public function testPropertyExpenseBills()
    {

    }

    /**
     * Test attribute "purchase_transactions"
     */
    public function testPropertyPurchaseTransactions()
    {

    }

    /**
     * Test attribute "adjustment_transactions"
     */
    public function testPropertyAdjustmentTransactions()
    {

    }

    /**
     * Test attribute "inventory_transfers"
     */
    public function testPropertyInventoryTransfers()
    {

    }

}
