<?php
/**
 * GLExportInventoryTransferTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Finance
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Finance API
 *
 * ConnectWise Finance API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\Finance;

/**
 * GLExportInventoryTransferTest Class Doc Comment
 *
 * @category    Class */
// * @description GLExportInventoryTransfer
/**
 * @package     Spinen\ConnectWise\Clients\Finance
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GLExportInventoryTransferTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "GLExportInventoryTransfer"
     */
    public function testGLExportInventoryTransfer()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "document_type"
     */
    public function testPropertyDocumentType()
    {

    }

    /**
     * Test attribute "document_date"
     */
    public function testPropertyDocumentDate()
    {

    }

    /**
     * Test attribute "account_number"
     */
    public function testPropertyAccountNumber()
    {

    }

    /**
     * Test attribute "gl_class"
     */
    public function testPropertyGlClass()
    {

    }

    /**
     * Test attribute "gl_type_id"
     */
    public function testPropertyGlTypeId()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "sales_code"
     */
    public function testPropertySalesCode()
    {

    }

    /**
     * Test attribute "memo"
     */
    public function testPropertyMemo()
    {

    }

    /**
     * Test attribute "cost_acccount_number"
     */
    public function testPropertyCostAcccountNumber()
    {

    }

    /**
     * Test attribute "inventory_account_number"
     */
    public function testPropertyInventoryAccountNumber()
    {

    }

    /**
     * Test attribute "transfer_id"
     */
    public function testPropertyTransferId()
    {

    }

    /**
     * Test attribute "item"
     */
    public function testPropertyItem()
    {

    }

    /**
     * Test attribute "gl_item_id"
     */
    public function testPropertyGlItemId()
    {

    }

    /**
     * Test attribute "sales_description"
     */
    public function testPropertySalesDescription()
    {

    }

    /**
     * Test attribute "item_description"
     */
    public function testPropertyItemDescription()
    {

    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {

    }

    /**
     * Test attribute "item_price"
     */
    public function testPropertyItemPrice()
    {

    }

    /**
     * Test attribute "taxable"
     */
    public function testPropertyTaxable()
    {

    }

    /**
     * Test attribute "unit_of_measure"
     */
    public function testPropertyUnitOfMeasure()
    {

    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {

    }

    /**
     * Test attribute "cost"
     */
    public function testPropertyCost()
    {

    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {

    }

    /**
     * Test attribute "sub_category"
     */
    public function testPropertySubCategory()
    {

    }

    /**
     * Test attribute "serialized_flag"
     */
    public function testPropertySerializedFlag()
    {

    }

    /**
     * Test attribute "serial_numbers"
     */
    public function testPropertySerialNumbers()
    {

    }

    /**
     * Test attribute "shipment_method"
     */
    public function testPropertyShipmentMethod()
    {

    }

    /**
     * Test attribute "bin"
     */
    public function testPropertyBin()
    {

    }

    /**
     * Test attribute "warehouse"
     */
    public function testPropertyWarehouse()
    {

    }

    /**
     * Test attribute "transfer_from_bin"
     */
    public function testPropertyTransferFromBin()
    {

    }

    /**
     * Test attribute "transfer_from_location_xref"
     */
    public function testPropertyTransferFromLocationXref()
    {

    }

    /**
     * Test attribute "transfer_to_bin"
     */
    public function testPropertyTransferToBin()
    {

    }

    /**
     * Test attribute "transfer_to_location_xref"
     */
    public function testPropertyTransferToLocationXref()
    {

    }

    /**
     * Test attribute "location_xref"
     */
    public function testPropertyLocationXref()
    {

    }

    /**
     * Test attribute "price_level_xref"
     */
    public function testPropertyPriceLevelXref()
    {

    }

    /**
     * Test attribute "uom_schedule_xref"
     */
    public function testPropertyUomScheduleXref()
    {

    }

    /**
     * Test attribute "item_type_xref"
     */
    public function testPropertyItemTypeXref()
    {

    }

    /**
     * Test attribute "inventory_xref"
     */
    public function testPropertyInventoryXref()
    {

    }

    /**
     * Test attribute "cogs_xref"
     */
    public function testPropertyCogsXref()
    {

    }

    /**
     * Test attribute "tax_note"
     */
    public function testPropertyTaxNote()
    {

    }

    /**
     * Test attribute "tax_code"
     */
    public function testPropertyTaxCode()
    {

    }

    /**
     * Test attribute "offset"
     */
    public function testPropertyOffset()
    {

    }

}
