<?php
/**
 * GLExportTransactionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Finance
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Finance API
 *
 * ConnectWise Finance API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\Finance;

/**
 * GLExportTransactionTest Class Doc Comment
 *
 * @category    Class */
// * @description GLExportTransaction
/**
 * @package     Spinen\ConnectWise\Clients\Finance
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GLExportTransactionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "GLExportTransaction"
     */
    public function testGLExportTransaction()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "gl_class"
     */
    public function testPropertyGlClass()
    {

    }

    /**
     * Test attribute "gl_type_id"
     */
    public function testPropertyGlTypeId()
    {

    }

    /**
     * Test attribute "document_date"
     */
    public function testPropertyDocumentDate()
    {

    }

    /**
     * Test attribute "document_number"
     */
    public function testPropertyDocumentNumber()
    {

    }

    /**
     * Test attribute "document_type"
     */
    public function testPropertyDocumentType()
    {

    }

    /**
     * Test attribute "memo"
     */
    public function testPropertyMemo()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "attention"
     */
    public function testPropertyAttention()
    {

    }

    /**
     * Test attribute "sales_territory"
     */
    public function testPropertySalesTerritory()
    {

    }

    /**
     * Test attribute "company"
     */
    public function testPropertyCompany()
    {

    }

    /**
     * Test attribute "company_type"
     */
    public function testPropertyCompanyType()
    {

    }

    /**
     * Test attribute "company_account_number"
     */
    public function testPropertyCompanyAccountNumber()
    {

    }

    /**
     * Test attribute "site"
     */
    public function testPropertySite()
    {

    }

    /**
     * Test attribute "billing_terms"
     */
    public function testPropertyBillingTerms()
    {

    }

    /**
     * Test attribute "billing_terms_xref"
     */
    public function testPropertyBillingTermsXref()
    {

    }

    /**
     * Test attribute "due_days"
     */
    public function testPropertyDueDays()
    {

    }

    /**
     * Test attribute "due_date"
     */
    public function testPropertyDueDate()
    {

    }

    /**
     * Test attribute "email_delivery_flag"
     */
    public function testPropertyEmailDeliveryFlag()
    {

    }

    /**
     * Test attribute "print_delivery_flag"
     */
    public function testPropertyPrintDeliveryFlag()
    {

    }

    /**
     * Test attribute "agreement_pre_payment_flag"
     */
    public function testPropertyAgreementPrePaymentFlag()
    {

    }

    /**
     * Test attribute "account_number"
     */
    public function testPropertyAccountNumber()
    {

    }

    /**
     * Test attribute "billing_type"
     */
    public function testPropertyBillingType()
    {

    }

    /**
     * Test attribute "gl_entry_ids"
     */
    public function testPropertyGlEntryIds()
    {

    }

    /**
     * Test attribute "purchase_order"
     */
    public function testPropertyPurchaseOrder()
    {

    }

    /**
     * Test attribute "project"
     */
    public function testPropertyProject()
    {

    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {

    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {

    }

    /**
     * Test attribute "sales_rep_id"
     */
    public function testPropertySalesRepId()
    {

    }

    /**
     * Test attribute "sales_rep_name"
     */
    public function testPropertySalesRepName()
    {

    }

    /**
     * Test attribute "taxable"
     */
    public function testPropertyTaxable()
    {

    }

    /**
     * Test attribute "taxable_total"
     */
    public function testPropertyTaxableTotal()
    {

    }

    /**
     * Test attribute "tax_code"
     */
    public function testPropertyTaxCode()
    {

    }

    /**
     * Test attribute "tax_group_rate"
     */
    public function testPropertyTaxGroupRate()
    {

    }

    /**
     * Test attribute "piggy_back_flag"
     */
    public function testPropertyPiggyBackFlag()
    {

    }

    /**
     * Test attribute "tax_account_number"
     */
    public function testPropertyTaxAccountNumber()
    {

    }

    /**
     * Test attribute "sales_tax"
     */
    public function testPropertySalesTax()
    {

    }

    /**
     * Test attribute "state_tax"
     */
    public function testPropertyStateTax()
    {

    }

    /**
     * Test attribute "county_tax"
     */
    public function testPropertyCountyTax()
    {

    }

    /**
     * Test attribute "city_tax"
     */
    public function testPropertyCityTax()
    {

    }

    /**
     * Test attribute "taxable_amount1"
     */
    public function testPropertyTaxableAmount1()
    {

    }

    /**
     * Test attribute "taxable_amount2"
     */
    public function testPropertyTaxableAmount2()
    {

    }

    /**
     * Test attribute "taxable_amount3"
     */
    public function testPropertyTaxableAmount3()
    {

    }

    /**
     * Test attribute "taxable_amount4"
     */
    public function testPropertyTaxableAmount4()
    {

    }

    /**
     * Test attribute "taxable_amount5"
     */
    public function testPropertyTaxableAmount5()
    {

    }

    /**
     * Test attribute "tax_agency_xref"
     */
    public function testPropertyTaxAgencyXref()
    {

    }

    /**
     * Test attribute "state_tax_xref"
     */
    public function testPropertyStateTaxXref()
    {

    }

    /**
     * Test attribute "county_tax_xref"
     */
    public function testPropertyCountyTaxXref()
    {

    }

    /**
     * Test attribute "tax_id"
     */
    public function testPropertyTaxId()
    {

    }

    /**
     * Test attribute "tax_dp_applied_flag"
     */
    public function testPropertyTaxDpAppliedFlag()
    {

    }

    /**
     * Test attribute "use_avalara_flag"
     */
    public function testPropertyUseAvalaraFlag()
    {

    }

    /**
     * Test attribute "send_avalara_tax_flag"
     */
    public function testPropertySendAvalaraTaxFlag()
    {

    }

    /**
     * Test attribute "ship_to_company"
     */
    public function testPropertyShipToCompany()
    {

    }

    /**
     * Test attribute "ship_company_account_number"
     */
    public function testPropertyShipCompanyAccountNumber()
    {

    }

    /**
     * Test attribute "ship_company_type"
     */
    public function testPropertyShipCompanyType()
    {

    }

    /**
     * Test attribute "ship_tax_id"
     */
    public function testPropertyShipTaxId()
    {

    }

    /**
     * Test attribute "ship_site"
     */
    public function testPropertyShipSite()
    {

    }

    /**
     * Test attribute "ship_contact"
     */
    public function testPropertyShipContact()
    {

    }

    /**
     * Test attribute "detail"
     */
    public function testPropertyDetail()
    {

    }

}
