<?php
/**
 * GLExportPurchaseTransactionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Finance
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Finance API
 *
 * ConnectWise Finance API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\Finance;

/**
 * GLExportPurchaseTransactionTest Class Doc Comment
 *
 * @category    Class */
// * @description GLExportPurchaseTransaction
/**
 * @package     Spinen\ConnectWise\Clients\Finance
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GLExportPurchaseTransactionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "GLExportPurchaseTransaction"
     */
    public function testGLExportPurchaseTransaction()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "document_date"
     */
    public function testPropertyDocumentDate()
    {

    }

    /**
     * Test attribute "document_number"
     */
    public function testPropertyDocumentNumber()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "memo"
     */
    public function testPropertyMemo()
    {

    }

    /**
     * Test attribute "ap_account_number"
     */
    public function testPropertyApAccountNumber()
    {

    }

    /**
     * Test attribute "purchase_date"
     */
    public function testPropertyPurchaseDate()
    {

    }

    /**
     * Test attribute "company"
     */
    public function testPropertyCompany()
    {

    }

    /**
     * Test attribute "company_type"
     */
    public function testPropertyCompanyType()
    {

    }

    /**
     * Test attribute "contact"
     */
    public function testPropertyContact()
    {

    }

    /**
     * Test attribute "site"
     */
    public function testPropertySite()
    {

    }

    /**
     * Test attribute "purchase_class"
     */
    public function testPropertyPurchaseClass()
    {

    }

    /**
     * Test attribute "freight_amount"
     */
    public function testPropertyFreightAmount()
    {

    }

    /**
     * Test attribute "freight_packing_slip"
     */
    public function testPropertyFreightPackingSlip()
    {

    }

    /**
     * Test attribute "packing_slip"
     */
    public function testPropertyPackingSlip()
    {

    }

    /**
     * Test attribute "dropship_flag"
     */
    public function testPropertyDropshipFlag()
    {

    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {

    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {

    }

    /**
     * Test attribute "billing_terms"
     */
    public function testPropertyBillingTerms()
    {

    }

    /**
     * Test attribute "billing_terms_xref"
     */
    public function testPropertyBillingTermsXref()
    {

    }

    /**
     * Test attribute "due_days"
     */
    public function testPropertyDueDays()
    {

    }

    /**
     * Test attribute "vendor_number"
     */
    public function testPropertyVendorNumber()
    {

    }

    /**
     * Test attribute "vendor_account_number"
     */
    public function testPropertyVendorAccountNumber()
    {

    }

    /**
     * Test attribute "vendor_invoice_date"
     */
    public function testPropertyVendorInvoiceDate()
    {

    }

    /**
     * Test attribute "vendor_invoice_number"
     */
    public function testPropertyVendorInvoiceNumber()
    {

    }

    /**
     * Test attribute "tax_agency_xref"
     */
    public function testPropertyTaxAgencyXref()
    {

    }

    /**
     * Test attribute "state_tax_xref"
     */
    public function testPropertyStateTaxXref()
    {

    }

    /**
     * Test attribute "county_tax_xref"
     */
    public function testPropertyCountyTaxXref()
    {

    }

    /**
     * Test attribute "city_tax_xref"
     */
    public function testPropertyCityTaxXref()
    {

    }

    /**
     * Test attribute "ship_to_company"
     */
    public function testPropertyShipToCompany()
    {

    }

    /**
     * Test attribute "ship_to_company_account_number"
     */
    public function testPropertyShipToCompanyAccountNumber()
    {

    }

    /**
     * Test attribute "ship_to_company_type"
     */
    public function testPropertyShipToCompanyType()
    {

    }

    /**
     * Test attribute "ship_to_contact"
     */
    public function testPropertyShipToContact()
    {

    }

    /**
     * Test attribute "ship_to_site"
     */
    public function testPropertyShipToSite()
    {

    }

    /**
     * Test attribute "ship_to_tax_group"
     */
    public function testPropertyShipToTaxGroup()
    {

    }

    /**
     * Test attribute "tax_code"
     */
    public function testPropertyTaxCode()
    {

    }

    /**
     * Test attribute "tax_group_rate"
     */
    public function testPropertyTaxGroupRate()
    {

    }

    /**
     * Test attribute "use_avalara_tax_flag"
     */
    public function testPropertyUseAvalaraTaxFlag()
    {

    }

    /**
     * Test attribute "purchase_header_tax_group"
     */
    public function testPropertyPurchaseHeaderTaxGroup()
    {

    }

    /**
     * Test attribute "purchase_header_taxable_flag"
     */
    public function testPropertyPurchaseHeaderTaxableFlag()
    {

    }

    /**
     * Test attribute "purchase_header_freight_taxable_flag"
     */
    public function testPropertyPurchaseHeaderFreightTaxableFlag()
    {

    }

    /**
     * Test attribute "purchase_detail"
     */
    public function testPropertyPurchaseDetail()
    {

    }

    /**
     * Test attribute "purchase_detail_tax"
     */
    public function testPropertyPurchaseDetailTax()
    {

    }

}
