<?php
/**
 * GLExportExpenseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Finance
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Finance API
 *
 * ConnectWise Finance API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\Finance;

/**
 * GLExportExpenseTest Class Doc Comment
 *
 * @category    Class */
// * @description GLExportExpense
/**
 * @package     Spinen\ConnectWise\Clients\Finance
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GLExportExpenseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "GLExportExpense"
     */
    public function testGLExportExpense()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "document_date"
     */
    public function testPropertyDocumentDate()
    {

    }

    /**
     * Test attribute "document_type"
     */
    public function testPropertyDocumentType()
    {

    }

    /**
     * Test attribute "ap_account_number"
     */
    public function testPropertyApAccountNumber()
    {

    }

    /**
     * Test attribute "ap_class"
     */
    public function testPropertyApClass()
    {

    }

    /**
     * Test attribute "account_number"
     */
    public function testPropertyAccountNumber()
    {

    }

    /**
     * Test attribute "gl_class"
     */
    public function testPropertyGlClass()
    {

    }

    /**
     * Test attribute "gl_type_id"
     */
    public function testPropertyGlTypeId()
    {

    }

    /**
     * Test attribute "memo"
     */
    public function testPropertyMemo()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "period_start_date"
     */
    public function testPropertyPeriodStartDate()
    {

    }

    /**
     * Test attribute "period_end_date"
     */
    public function testPropertyPeriodEndDate()
    {

    }

    /**
     * Test attribute "member"
     */
    public function testPropertyMember()
    {

    }

    /**
     * Test attribute "vendor_number"
     */
    public function testPropertyVendorNumber()
    {

    }

    /**
     * Test attribute "company"
     */
    public function testPropertyCompany()
    {

    }

    /**
     * Test attribute "company_account_number"
     */
    public function testPropertyCompanyAccountNumber()
    {

    }

    /**
     * Test attribute "project"
     */
    public function testPropertyProject()
    {

    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {

    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {

    }

    /**
     * Test attribute "offset"
     */
    public function testPropertyOffset()
    {

    }

}
