<?php
/**
 * InvoiceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Finance
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Finance API
 *
 * ConnectWise Finance API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\Finance;

/**
 * InvoiceTest Class Doc Comment
 *
 * @category    Class */
// * @description Invoice
/**
 * @package     Spinen\ConnectWise\Clients\Finance
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InvoiceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Invoice"
     */
    public function testInvoice()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "invoice_number"
     */
    public function testPropertyInvoiceNumber()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

    /**
     * Test attribute "company"
     */
    public function testPropertyCompany()
    {

    }

    /**
     * Test attribute "bill_to_company"
     */
    public function testPropertyBillToCompany()
    {

    }

    /**
     * Test attribute "ship_to_company"
     */
    public function testPropertyShipToCompany()
    {

    }

    /**
     * Test attribute "apply_to_type"
     */
    public function testPropertyApplyToType()
    {

    }

    /**
     * Test attribute "apply_to_id"
     */
    public function testPropertyApplyToId()
    {

    }

    /**
     * Test attribute "attention"
     */
    public function testPropertyAttention()
    {

    }

    /**
     * Test attribute "billing_site"
     */
    public function testPropertyBillingSite()
    {

    }

    /**
     * Test attribute "shipping_site"
     */
    public function testPropertyShippingSite()
    {

    }

    /**
     * Test attribute "billing_terms"
     */
    public function testPropertyBillingTerms()
    {

    }

    /**
     * Test attribute "reference"
     */
    public function testPropertyReference()
    {

    }

    /**
     * Test attribute "customer_po"
     */
    public function testPropertyCustomerPo()
    {

    }

    /**
     * Test attribute "template_setup_id"
     */
    public function testPropertyTemplateSetupId()
    {

    }

    /**
     * Test attribute "email_template_id"
     */
    public function testPropertyEmailTemplateId()
    {

    }

    /**
     * Test attribute "add_to_batch_email_list"
     */
    public function testPropertyAddToBatchEmailList()
    {

    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {

    }

    /**
     * Test attribute "restrict_downpayment_flag"
     */
    public function testPropertyRestrictDownpaymentFlag()
    {

    }

    /**
     * Test attribute "location_id"
     */
    public function testPropertyLocationId()
    {

    }

    /**
     * Test attribute "department_id"
     */
    public function testPropertyDepartmentId()
    {

    }

    /**
     * Test attribute "territory_id"
     */
    public function testPropertyTerritoryId()
    {

    }

    /**
     * Test attribute "top_comment"
     */
    public function testPropertyTopComment()
    {

    }

    /**
     * Test attribute "bottom_comment"
     */
    public function testPropertyBottomComment()
    {

    }

    /**
     * Test attribute "taxable_flag"
     */
    public function testPropertyTaxableFlag()
    {

    }

    /**
     * Test attribute "tax_code"
     */
    public function testPropertyTaxCode()
    {

    }

    /**
     * Test attribute "internal_notes"
     */
    public function testPropertyInternalNotes()
    {

    }

    /**
     * Test attribute "downpayment_previously_taxed_flag"
     */
    public function testPropertyDownpaymentPreviouslyTaxedFlag()
    {

    }

    /**
     * Test attribute "service_total"
     */
    public function testPropertyServiceTotal()
    {

    }

    /**
     * Test attribute "due_date"
     */
    public function testPropertyDueDate()
    {

    }

    /**
     * Test attribute "expense_total"
     */
    public function testPropertyExpenseTotal()
    {

    }

    /**
     * Test attribute "product_total"
     */
    public function testPropertyProductTotal()
    {

    }

    /**
     * Test attribute "previous_progress_applied"
     */
    public function testPropertyPreviousProgressApplied()
    {

    }

    /**
     * Test attribute "service_adjustment_amount"
     */
    public function testPropertyServiceAdjustmentAmount()
    {

    }

    /**
     * Test attribute "agreement_amount"
     */
    public function testPropertyAgreementAmount()
    {

    }

    /**
     * Test attribute "downpayment_applied"
     */
    public function testPropertyDownpaymentApplied()
    {

    }

    /**
     * Test attribute "subtotal"
     */
    public function testPropertySubtotal()
    {

    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {

    }

    /**
     * Test attribute "remaining_downpayment"
     */
    public function testPropertyRemainingDownpayment()
    {

    }

    /**
     * Test attribute "sales_tax"
     */
    public function testPropertySalesTax()
    {

    }

    /**
     * Test attribute "adjustment_reason"
     */
    public function testPropertyAdjustmentReason()
    {

    }

    /**
     * Test attribute "adjusted_by"
     */
    public function testPropertyAdjustedBy()
    {

    }

    /**
     * Test attribute "payments"
     */
    public function testPropertyPayments()
    {

    }

    /**
     * Test attribute "credits"
     */
    public function testPropertyCredits()
    {

    }

    /**
     * Test attribute "balance"
     */
    public function testPropertyBalance()
    {

    }

    /**
     * Test attribute "special_invoice_flag"
     */
    public function testPropertySpecialInvoiceFlag()
    {

    }

    /**
     * Test attribute "_info"
     */
    public function testPropertyInfo()
    {

    }

}
