<?php
/**
 * TaxCodeXRefTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Finance
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Finance API
 *
 * ConnectWise Finance API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\Finance;

/**
 * TaxCodeXRefTest Class Doc Comment
 *
 * @category    Class */
// * @description TaxCodeXRef
/**
 * @package     Spinen\ConnectWise\Clients\Finance
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TaxCodeXRefTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "TaxCodeXRef"
     */
    public function testTaxCodeXRef()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "default_flag"
     */
    public function testPropertyDefaultFlag()
    {

    }

    /**
     * Test attribute "level_one"
     */
    public function testPropertyLevelOne()
    {

    }

    /**
     * Test attribute "level_two"
     */
    public function testPropertyLevelTwo()
    {

    }

    /**
     * Test attribute "level_three"
     */
    public function testPropertyLevelThree()
    {

    }

    /**
     * Test attribute "level_four"
     */
    public function testPropertyLevelFour()
    {

    }

    /**
     * Test attribute "level_five"
     */
    public function testPropertyLevelFive()
    {

    }

    /**
     * Test attribute "tax_code"
     */
    public function testPropertyTaxCode()
    {

    }

    /**
     * Test attribute "_info"
     */
    public function testPropertyInfo()
    {

    }

}
