<?php
/**
 * UnpostedInvoiceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Finance
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Finance API
 *
 * ConnectWise Finance API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\Finance;

/**
 * UnpostedInvoiceTest Class Doc Comment
 *
 * @category    Class */
// * @description UnpostedInvoice
/**
 * @package     Spinen\ConnectWise\Clients\Finance
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UnpostedInvoiceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "UnpostedInvoice"
     */
    public function testUnpostedInvoice()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "billing_log_id"
     */
    public function testPropertyBillingLogId()
    {

    }

    /**
     * Test attribute "location_id"
     */
    public function testPropertyLocationId()
    {

    }

    /**
     * Test attribute "department_id"
     */
    public function testPropertyDepartmentId()
    {

    }

    /**
     * Test attribute "company"
     */
    public function testPropertyCompany()
    {

    }

    /**
     * Test attribute "account_number"
     */
    public function testPropertyAccountNumber()
    {

    }

    /**
     * Test attribute "bill_to_company"
     */
    public function testPropertyBillToCompany()
    {

    }

    /**
     * Test attribute "bill_to_site"
     */
    public function testPropertyBillToSite()
    {

    }

    /**
     * Test attribute "ship_to_company"
     */
    public function testPropertyShipToCompany()
    {

    }

    /**
     * Test attribute "ship_to_site"
     */
    public function testPropertyShipToSite()
    {

    }

    /**
     * Test attribute "invoice_number"
     */
    public function testPropertyInvoiceNumber()
    {

    }

    /**
     * Test attribute "invoice_date"
     */
    public function testPropertyInvoiceDate()
    {

    }

    /**
     * Test attribute "invoice_type"
     */
    public function testPropertyInvoiceType()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "billing_terms"
     */
    public function testPropertyBillingTerms()
    {

    }

    /**
     * Test attribute "due_days"
     */
    public function testPropertyDueDays()
    {

    }

    /**
     * Test attribute "due_date"
     */
    public function testPropertyDueDate()
    {

    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {

    }

    /**
     * Test attribute "sub_total"
     */
    public function testPropertySubTotal()
    {

    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {

    }

    /**
     * Test attribute "invoice_taxable_flag"
     */
    public function testPropertyInvoiceTaxableFlag()
    {

    }

    /**
     * Test attribute "tax_code"
     */
    public function testPropertyTaxCode()
    {

    }

    /**
     * Test attribute "avalara_tax_flag"
     */
    public function testPropertyAvalaraTaxFlag()
    {

    }

    /**
     * Test attribute "item_taxable_flag"
     */
    public function testPropertyItemTaxableFlag()
    {

    }

    /**
     * Test attribute "sales_tax_amount"
     */
    public function testPropertySalesTaxAmount()
    {

    }

    /**
     * Test attribute "state_tax_flag"
     */
    public function testPropertyStateTaxFlag()
    {

    }

    /**
     * Test attribute "state_tax_xref"
     */
    public function testPropertyStateTaxXref()
    {

    }

    /**
     * Test attribute "state_tax_amount"
     */
    public function testPropertyStateTaxAmount()
    {

    }

    /**
     * Test attribute "county_tax_flag"
     */
    public function testPropertyCountyTaxFlag()
    {

    }

    /**
     * Test attribute "county_tax_xref"
     */
    public function testPropertyCountyTaxXref()
    {

    }

    /**
     * Test attribute "county_tax_amount"
     */
    public function testPropertyCountyTaxAmount()
    {

    }

    /**
     * Test attribute "city_tax_flag"
     */
    public function testPropertyCityTaxFlag()
    {

    }

    /**
     * Test attribute "city_tax_xref"
     */
    public function testPropertyCityTaxXref()
    {

    }

    /**
     * Test attribute "city_tax_amount"
     */
    public function testPropertyCityTaxAmount()
    {

    }

    /**
     * Test attribute "country_tax_flag"
     */
    public function testPropertyCountryTaxFlag()
    {

    }

    /**
     * Test attribute "country_tax_xref"
     */
    public function testPropertyCountryTaxXref()
    {

    }

    /**
     * Test attribute "country_tax_amount"
     */
    public function testPropertyCountryTaxAmount()
    {

    }

    /**
     * Test attribute "composite_tax_flag"
     */
    public function testPropertyCompositeTaxFlag()
    {

    }

    /**
     * Test attribute "composite_tax_xref"
     */
    public function testPropertyCompositeTaxXref()
    {

    }

    /**
     * Test attribute "composite_tax_amount"
     */
    public function testPropertyCompositeTaxAmount()
    {

    }

    /**
     * Test attribute "created_by"
     */
    public function testPropertyCreatedBy()
    {

    }

    /**
     * Test attribute "date_closed"
     */
    public function testPropertyDateClosed()
    {

    }

    /**
     * Test attribute "_info"
     */
    public function testPropertyInfo()
    {

    }

}
