<?php
/**
 * AgreementWorkRoleExclusionsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Finance
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Finance API
 *
 * ConnectWise Finance API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Spinen\ConnectWise\Clients\Finance;

use \Spinen\ConnectWise\Clients\Finance\Configuration;
use \Spinen\ConnectWise\Clients\Finance\ApiClient;
use \Spinen\ConnectWise\Clients\Finance\ApiException;
use \Spinen\ConnectWise\Clients\Finance\ObjectSerializer;

/**
 * AgreementWorkRoleExclusionsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Finance
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AgreementWorkRoleExclusionsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for financeAgreementsIdWorkRoleExclusionsCountGet
     *
     * .
     *
     */
    public function testFinanceAgreementsIdWorkRoleExclusionsCountGet()
    {

    }

    /**
     * Test case for financeAgreementsIdWorkRoleExclusionsGet
     *
     * .
     *
     */
    public function testFinanceAgreementsIdWorkRoleExclusionsGet()
    {

    }

    /**
     * Test case for financeAgreementsIdWorkRoleExclusionsPost
     *
     * .
     *
     */
    public function testFinanceAgreementsIdWorkRoleExclusionsPost()
    {

    }

    /**
     * Test case for financeAgreementsIdWorkRoleExclusionsWorkRoleExclusionIdDelete
     *
     * .
     *
     */
    public function testFinanceAgreementsIdWorkRoleExclusionsWorkRoleExclusionIdDelete()
    {

    }

}
