<?php
/**
 * AgreementBoardDefaultsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Finance
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Finance API
 *
 * ConnectWise Finance API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Spinen\ConnectWise\Clients\Finance;

use \Spinen\ConnectWise\Clients\Finance\Configuration;
use \Spinen\ConnectWise\Clients\Finance\ApiClient;
use \Spinen\ConnectWise\Clients\Finance\ApiException;
use \Spinen\ConnectWise\Clients\Finance\ObjectSerializer;

/**
 * AgreementBoardDefaultsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Finance
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AgreementBoardDefaultsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for financeAgreementsIdBoardDefaultsBoardDefaultIdDelete
     *
     * .
     *
     */
    public function testFinanceAgreementsIdBoardDefaultsBoardDefaultIdDelete()
    {

    }

    /**
     * Test case for financeAgreementsIdBoardDefaultsBoardDefaultIdGet
     *
     * .
     *
     */
    public function testFinanceAgreementsIdBoardDefaultsBoardDefaultIdGet()
    {

    }

    /**
     * Test case for financeAgreementsIdBoardDefaultsBoardDefaultIdPatch
     *
     * .
     *
     */
    public function testFinanceAgreementsIdBoardDefaultsBoardDefaultIdPatch()
    {

    }

    /**
     * Test case for financeAgreementsIdBoardDefaultsBoardDefaultIdPut
     *
     * .
     *
     */
    public function testFinanceAgreementsIdBoardDefaultsBoardDefaultIdPut()
    {

    }

    /**
     * Test case for financeAgreementsIdBoardDefaultsCountGet
     *
     * .
     *
     */
    public function testFinanceAgreementsIdBoardDefaultsCountGet()
    {

    }

    /**
     * Test case for financeAgreementsIdBoardDefaultsGet
     *
     * .
     *
     */
    public function testFinanceAgreementsIdBoardDefaultsGet()
    {

    }

    /**
     * Test case for financeAgreementsIdBoardDefaultsPost
     *
     * .
     *
     */
    public function testFinanceAgreementsIdBoardDefaultsPost()
    {

    }

}
